#!/usr/bin/env bash

if [ -z "$(docker images -q mwfractal:asciiart 2> /dev/null)" ]; then
  docker build -f Dockerfile . -t mwfractal:asciiart --target asciiart
fi

docker run --rm -t mwfractal:asciiart "$@"
