name: Build mwfractal

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docker-build:
    runs-on: ubuntu-latest
    name: Build mwfractal in docker
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: expose github runtime for docker build caching configs
        uses: actions/github-script@v7
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            core.exportVariable("ACTIONS_CACHE_URL", process.env["ACTIONS_CACHE_URL"])
            core.exportVariable("ACTIONS_RUNTIME_TOKEN", process.env["ACTIONS_RUNTIME_TOKEN"])
            core.exportVariable("ACTIONS_RUNTIME_URL", process.env["ACTIONS_RUNTIME_URL"])

      - name: build the image
        run: docker buildx build \
          --target mwfractal \
          -t cjw6k/mwfractal \
          -f Dockerfile \
          --cache-to type=gha,scope=image \
          --cache-from type=gha,scope=image \
          .
